#!/bin/sh -eu

cd "$(dirname "$0")/.."

get()
(
    url="$1"
    dest="${url##*/}"
    echo
    echo "GETTING LATEST: $url"
    curl \
        "$url" \
        > "nix/arduino/$dest"
)

for url in \
    https://downloads.arduino.cc/libraries/library_index.json \
    https://downloads.arduino.cc/libraries/library_index.json.sig \
    https://downloads.arduino.cc/packages/package_index.json \
    https://downloads.arduino.cc/packages/package_index.json.sig \
    https://raw.githubusercontent.com/keyboardio/boardsmanager/master/devel/package_kaleidoscope_devel_index.json
do get "$url"
done
