#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --keep HOME \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file nix \
    nix-project.nix-project-org2gfm \
    nixpkgs-stable.ansifilter \
    nixpkgs-stable.bash \
    nixpkgs-stable.coreutils \
    nixpkgs-stable.gnugrep \
    nixpkgs-stable.procps \
    nixpkgs-stable.tree \
    --command \
    org2gfm \
    --exclude links.org \
    --exclude nix.mac.org \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
