#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --keep HOME \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file nix \
    nix-project-org2gfm \
    pkgs-stable.ansifilter \
    pkgs-stable.bash \
    pkgs-stable.coreutils \
    pkgs-stable.gnugrep \
    pkgs-stable.gnutar \
    pkgs-stable.gzip \
    pkgs-stable.procps \
    pkgs-stable.tree \
    --command \
    org2gfm \
    --ignore 'links.org' \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
