#!/bin/sh -eu


export KALEIDOSCOPE_DIR=/tmp/kaleidoscope
export VERBOSE=1


cd "$(dirname "$0")/.."

rm -rf "$KALEIDOSCOPE_DIR"

git clone https://github.com/keyboardio/Kaleidoscope.git \
    "$KALEIDOSCOPE_DIR"

git -C "$KALEIDOSCOPE_DIR" submodule update --init

cd "$KALEIDOSCOPE_DIR"

nix shell nixpkgs#arduino-cli --command \
    make -C "$KALEIDOSCOPE_DIR" setup \
    2> "/tmp/kaleidoscope.make.$(date +%Y%m%d).err" \
    > "/tmp/kaleidoscope.make.$(date +%Y%m%d).out"

exa --tree "$KALEIDOSCOPE_DIR/.arduino/downloads/" \
    > "/tmp/kaleidoscope.deps.$(date +%Y%m%d)"
