#+title: Support for Project Maintenance
#+setupfile: ../doc/internal/links.org

The files in this directory support the maintenance of the project. You can
safely ignore this directory if you only want to use the project.

There are three scripts in this directory.

- =arduino-upgrade=
- =kaleidoscope-deps=
- =docs-generate=

They are designed to be called with no arguments, and can be called from any
working directory, though some modify the source code in place.

=arduino-upgrade= updates the binary signatures in
[[../nix/arduino][=../nix/arduino=]].  Annoyingly, these signatures change
rapidly upstream for what appears to be an embedded timestamp.  That creates too
much hash-changing churn in trying to pull them in as flake inputs.

=kaleidoscope-deps= sets up Kaleidoscope as per the official documentation, so
we can see what inputs we need to update/pin in [[../flake.nix][=../flake.nix=]].
This build happens in =/tmp=

=docs-generate= will execute any ~SRC~ blocks in Org-mode files, modifying them
in place. And then it generates GitHub Flavored Markdown files from them.
