#!/bin/sh -eu

cd "$(dirname "$0")"

nix run \
    --ignore-environment \
    --file nix \
    shajra-keyboards-flash-scripts.moonlander \
    --command \
    flash-moonlander \
    --nix "$(command -v nix)" \
    "$@"
