#!/bin/sh -eu


PROJECT_ROOT="$(dirname "$0")"
RUN_SH="$PROJECT_ROOT/common/run.sh"
BUILD_NIX="$PROJECT_ROOT/ergodox_ez"
KEYBOARD_ID="ergodoxez"
KEYBOARD_DESC="ZSA Technology Lab's Ergodox EZ"


. "$RUN_SH"
