#!/bin/sh -eu

cd "$(dirname "$0")"

nix run \
    --ignore-environment \
    --keep HOME \
    --file nix \
    shajra-keyboards-flash-scripts.model01 \
    --command \
    flash-model01 \
    --nix "$(command -v nix)" \
    "$@"
