#!/bin/sh -eu

cd "$(dirname "$0")"

nix --extra-experimental-features "nix-command flakes" \
    shell \
    --ignore-environment \
    .#flash-moonlander \
    --command \
    flash-moonlander \
    --nix "$(command -v nix)" \
    "$@"
