#!/bin/sh -eu


PROJECT_ROOT="$(dirname "$0")"
LICENSE_NIX="$PROJECT_ROOT/common/licenses.nix"


nix run \
    --ignore-environment \
    --file "$LICENSE_NIX" \
    --command shajra-keyboards-licenses
